# Generated by Django 6.0.5 on 2026-05-28 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_CSV', 'Utility Portal Export'), ('CONCUR_TRAVEL', 'Corporate Travel API')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='esg_pipeline.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='The exact, unmodified JSON/dict from the source (SAP, Utility, Travel).')),
                ('activity_date_start', models.DateField(blank=True, null=True)),
                ('activity_date_end', models.DateField(blank=True, null=True)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('co2_equivalent_tons', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect - Energy)'), ('SCOPE_3', 'Scope 3 (Value Chain)'), ('UNASSIGNED', 'Pending Categorization')], default='UNASSIGNED', max_length=20)),
                ('status', models.CharField(choices=[('STAGING', 'Raw / Processing'), ('PENDING_REVIEW', 'Pending Analyst Review'), ('APPROVED', 'Approved & Locked'), ('REJECTED', 'Rejected')], default='STAGING', max_length=20)),
                ('data_quality_flags', models.JSONField(blank=True, default=list, help_text="List of strings flagging issues, e.g., ['UNRECOGNIZED_UNIT', 'SUSPICIOUS_HIGH_VALUE']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='esg_pipeline.dataingestionrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='esg_pipeline.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField()),
                ('justification', models.TextField(blank=True, help_text='Why the analyst made this change.')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg_pipeline.emissionrecord')),
            ],
        ),
    ]
